apps/serverstatus/urls.py
from django.urls import URLPattern
from django.urls import URLResolver
from django.urls import path

from . import views

app_name = 'serverstatus'

urlpatterns: list[URLPattern | URLResolver] = [
    path('current-status/', views.current_status, name='current-status'),
]

apps/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('characters/', views.characters, name='characters'),
    path('characters/redirect/', views.character_redirect, name='character_redirect'),
    path(
        'character/<int:character_id>/<int:token_id>/delete/',
        views.character_delete,
        name='character_delete',
    ),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import URLPattern
from django.urls import URLResolver
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView

urlpatterns: list[URLPattern | URLResolver] = [
    path('', TemplateView.as_view(template_name='landing.html'), name='landing'),
    path('terms', TemplateView.as_view(template_name='terms.html'), name='terms'),
    path('ccp', TemplateView.as_view(template_name='ccp.html'), name='ccp'),
    path('sso/', include('apps.esi.urls', namespace='esi')),
    path('accounts/', include('allauth.urls')),
    path('teams/', include('organizations.urls')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('market/', include('apps.market.urls', namespace='market')),
    path('admin/', admin.site.urls),
    path(
        'serverstatus/',
        include('apps.serverstatus.urls', namespace='serverstatus'),
    ),
]


if not settings.TEST:
    urlpatterns = [*urlpatterns, path('', include('django_prometheus.urls'))]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    if 'debug_toolbar' in settings.INSTALLED_APPS and settings.TEST is not True:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), *urlpatterns]

apps/templates/cotton/footer.html
<footer class="footer sm:footer-horizontal footer-center bg-base-300 text-base-content p-4">
  <aside>
    <p>Copyright © {% now "Y" %} - All right reserved by DriftNet</p>
    <p>
      <a href="{% url 'terms' %}" class="hover:underline">Terms of Service</a>
      <span class="mx-2 text-muted">·</span>
      <a href="{% url 'ccp' %}" class="hover:underline">CCP / EVE Disclaimer</a>
    </p>
  </aside>
</footer>

apps/templates/cotton/navbar.html
<div class="navbar bg-base-200 shadow-lg">
  <div class="navbar-start">
    <a class="btn btn-ghost text-xl">DriftNet</a>
  </div>
  <div class="navbar-center hidden lg:flex">
    <ul class="menu menu-horizontal px-1">
      {% if user.is_authenticated %}
        <li>
          <a>Item 1</a>
        </li>
        <li>
          <details>
            <summary>Parent</summary>
            <ul class="p-2">
              <li>
                <a>Submenu 1</a>
              </li>
              <li>
                <a>Submenu 2</a>
              </li>
            </ul>
          </details>
        </li>
        <li>
          <a>Item 3</a>
        </li>
      {% else %}
        <li>
          <a href="{% url 'landing' %}">Home</a>
        </li>
      {% endif %}
    </ul>
  </div>
  <div class="navbar-end">
    <div id="server-status-display"
         hx-get="{% url 'serverstatus:current-status' %}"
         hx-trigger="load, every 60s"></div>
    {% if user.is_authenticated %}
      <div class="dropdown dropdown-end">
        <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <svg data-jdenticon-value="{{ user.username }}" width="40" height="40">
            </svg>
          </div>
        </div>
        <ul tabindex="0"
            class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-25 p-2 shadow">
          <li>
            <a>Profile</a>
          </li>
          <li>
            <a href="{% url 'users:characters' %}">Characters</a>
          </li>
          <li>
            <a>Settings</a>
          </li>
          <li>
            <a href="{% url 'account_logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    {% else %}
      <a class="btn btn-soft btn-accent ml-2" href="{% url 'account_login' %}">Login</a>
      <a class="btn btn-info ml-2" href="{% url 'account_signup' %}">Sign Up</a>
    {% endif %}
  </div>
</div>