apps/market/urls.py
from django.urls import path

from . import views

app_name = 'market'

urlpatterns = [
    path('', views.market_index, name='market_index'),
    path('_/item-details/<int:item_id>/', views.item_details, name='item-details'),
    path('_/market-sidebar/', views.market_sidebar, name='market-sidebar'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import URLPattern
from django.urls import URLResolver
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView

urlpatterns: list[URLPattern | URLResolver] = [
    path('', TemplateView.as_view(template_name='landing.html'), name='landing'),
    path('terms', TemplateView.as_view(template_name='terms.html'), name='terms'),
    path('ccp', TemplateView.as_view(template_name='ccp.html'), name='ccp'),
    path('sso/', include('apps.esi.urls', namespace='esi')),
    path('accounts/', include('allauth.urls')),
    path('teams/', include('organizations.urls')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('market/', include('apps.market.urls', namespace='market')),
    path('admin/', admin.site.urls),
    path(
        'serverstatus/',
        include('apps.serverstatus.urls', namespace='serverstatus'),
    ),
]


if not settings.TEST:
    urlpatterns = [*urlpatterns, path('', include('django_prometheus.urls'))]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    if 'debug_toolbar' in settings.INSTALLED_APPS and settings.TEST is not True:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), *urlpatterns]

apps/market/models/market_group_with_types.py
from django.db import models


class MarketGroupWithTypes(models.Model):
    market_group_id = models.IntegerField(primary_key=True)
    market_group_name = models.CharField(max_length=255)
    parent_group_id = models.IntegerField(null=True)
    type_id = models.IntegerField(null=True)
    type_name = models.CharField(max_length=255, null=True)

    class Meta:
        managed = False
        db_table = 'market_group_with_types'

apps/market/views.py
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET

from apps.market.view_helpers import build_market_tree


# Create your views here.
def market_index(request: HttpRequest) -> HttpResponse:
    return render(
        request,
        'market-index.html',
    )


@require_GET
def item_details(request: HttpRequest, item_id: int) -> HttpResponse:
    # Placeholder implementation for item details
    # In a real application, you would fetch item details from the database
    item = {
        'id': item_id,
        'name': f'Item {item_id}',
        'description': f'Description for item {item_id}',
        'price': f'${item_id * 10}.00',
    }
    return render(
        request,
        'partials/market-item-details.html',
        context=item,
    )


@require_GET
def market_sidebar(request: HttpRequest) -> HttpResponse:
    market_groups = build_market_tree()
    return render(
        request,
        'partials/market-sidebar.html',
        {'market_groups': market_groups},
    )

apps/market/templates/market-index.html
<c-layouts.market>
<div class="flex flex-row min-h-screen">
  {% comment %} <div class="flex-none bg-base-200">{% include "market-sidebar.html" %}</div> {% endcomment %}
  <div hx-get="{% url 'market:market-sidebar' %}"
       hx-trigger="load"
       hx-target="this"
       hx-swap="innerHTML"
       class="flex-none bg-base-200">
    <ul class="menu bg-base-200 rounded-box min-w-65">
      <li class="menu-title">
        <span class="font-semibold text-center">Market</span>
      </li>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
      <div class="skeleton h-6 w-full mb-2"></div>
    </ul>
  </div>
  <div class="flex-1 flex-col bg-base-300">
    <c-market-item-details />
    <div class="flex flex-col h-full w-full mt-1">
      <ul id="market-detail-options"
          class="menu menu-vertical lg:menu-horizontal bg-base-200 rounded-box p-2 shadow-lg">
        <li>
          <a href="#">Market Overview</a>
        </li>
        <li>
          <a href="#">My Orders</a>
        </li>
        <li>
          <a href="#">Order History</a>
        </li>
        <li>
          <a href="#">Watchlist</a>
        </li>
      </ul>
      <div id="market-item-details-div">
        <div class="justify-center items-center h-full w-full mt-8">
          <p class="text-center text-lg italic text-base-content/50">
            Please select an item from the market groups on the left to view market details.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
</c-layouts.market>

apps/market/templates/market-sidebar-group.html
<li>
  <details>
    <summary>{{ group.name }}</summary>
    <ul>
      {% for subgroup in group.children %}
        {% if subgroup.children|length > 0 %}
          {% include "market-sidebar-group.html" with group=subgroup %}
        {% else %}
          <li>
            <details>
              <summary>{{ subgroup.name }}</summary>
              <ul>
                {% for market_item in subgroup.market_items %}
                  <li>
                    <a href="#" class="hover:underline">{{ market_item.item_name }}</a>
                  </li>
                {% endfor %}
              </ul>
            </details>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </details>
</li>

apps/market/templates/market-sidebar.html
<ul class="menu bg-base-200 rounded-box min-w-56">
  <li class="menu-title">
    <span class="font-semibold text-center">Market</span>
  </li>
  {% for market_group in market_groups|dictsort:"name" %}
    {% include "market-sidebar-group.html" with group=market_group %}
  {% endfor %}
</ul>